import {
  createDefaultHysteriaClient,
  createDefaultHysteriaInboundSettings,
  createDefaultTrojanClient,
  createDefaultTrojanInboundSettings,
  createDefaultVlessClient,
  createDefaultVlessInboundSettings,
  createDefaultVmessClient,
  createDefaultVmessInboundSettings,
} from '@/lib/xray/inbound-defaults';
import type { RawInboundRow } from '@/lib/xray/inbound-form-adapter';
import { getRandomRealityTarget } from '@/models/reality-targets';
import { RealityStreamSettingsSchema, TlsStreamSettingsSchema } from '@/schemas/protocols/security';
import {
  GrpcStreamSettingsSchema,
  HysteriaStreamSettingsSchema,
  TcpStreamSettingsSchema,
  WsStreamSettingsSchema,
} from '@/schemas/protocols/stream';
import { RandomUtil } from '@/utils';

// One-click inbound presets. Each preset turns a single click into a full,
// ready-to-save inbound config: protocol + transport + security + one default
// client + a random port. The modal feeds the returned row through
// rawInboundToFormValues() — the exact same path buildAddModeValues() uses —
// so every preset rides the existing form validation and submit pipeline.
//
// Two flags drive post-apply work the modal owns:
//   - needsRealityKeys: the modal fetches GET /panel/api/server/getNewX25519Cert
//     and injects privateKey/publicKey after applying (Reality keys are
//     generated by the xray binary, not in the browser).
//   - needsDomain: the preset is TLS-based and the share link won't work until
//     the operator points a domain at this server and installs a cert. The
//     modal surfaces a domain input; the typed value lands in serverName/SNI.

export type PresetId =
  | 'vless-reality-vision'
  | 'vless-reality-grpc'
  | 'hysteria2'
  | 'trojan-tls'
  | 'vmess-ws-tls';

export interface InboundPreset {
  id: PresetId;
  // i18n keys resolved by the modal (falls back to the literal if missing).
  titleKey: string;
  descKey: string;
  recommended?: boolean;
  needsRealityKeys: boolean;
  needsDomain: boolean;
  // domain is supplied only for needsDomain presets; ignored otherwise.
  build: (domain?: string) => RawInboundRow;
}

function randomPort(): number {
  return RandomUtil.randomInteger(10000, 60000);
}

function csvToList(value: string): string[] {
  return value.split(',').map((s) => s.trim()).filter(Boolean);
}

// A Reality stream block seeded with a random camouflage target, fresh
// shortIds, and an empty key pair. The modal fills privateKey/publicKey after
// fetching them from the panel.
function realityStream(network: 'tcp' | 'grpc'): Record<string, unknown> {
  const tgt = getRandomRealityTarget();
  const reality = RealityStreamSettingsSchema.parse({}) as Record<string, unknown>;
  reality.target = tgt.target;
  reality.serverNames = csvToList(tgt.sni);
  reality.shortIds = csvToList(RandomUtil.randomShortIds());

  const stream: Record<string, unknown> = { network, security: 'reality', realitySettings: reality };
  if (network === 'tcp') {
    stream.tcpSettings = TcpStreamSettingsSchema.parse({ header: { type: 'none' } });
  } else {
    stream.grpcSettings = GrpcStreamSettingsSchema.parse({ serviceName: RandomUtil.randomLowerAndNum(8) });
  }
  return stream;
}

// An empty file-backed cert slot. TLS presets ship one of these so the form
// always has a certificates[0] to write into — the modal auto-fills its
// certificateFile/keyFile from the panel's own cert when the preset is
// applied, making TLS presets one-click on a panel that already has SSL.
function emptyFileCert(): Record<string, unknown> {
  return {
    useFile: true,
    certificateFile: '',
    keyFile: '',
    certificate: [],
    key: [],
    oneTimeLoading: false,
    usage: 'encipherment',
    buildChain: false,
  };
}

// A TLS stream block. serverName carries the domain (also the SNI clients
// send). certificates carries one empty file-cert slot for the modal to
// auto-fill from the panel cert.
function tlsStream(network: Record<string, unknown>, domain?: string): Record<string, unknown> {
  const tls = TlsStreamSettingsSchema.parse({}) as Record<string, unknown>;
  tls.serverName = (domain ?? '').trim();
  tls.certificates = [emptyFileCert()];
  return { ...network, security: 'tls', tlsSettings: tls };
}

export const INBOUND_PRESETS: readonly InboundPreset[] = [
  {
    id: 'vless-reality-vision',
    titleKey: 'pages.inbounds.presets.vlessRealityVision.title',
    descKey: 'pages.inbounds.presets.vlessRealityVision.desc',
    recommended: true,
    needsRealityKeys: true,
    needsDomain: false,
    build: () => {
      const settings = createDefaultVlessInboundSettings();
      settings.clients = [createDefaultVlessClient({ flow: 'xtls-rprx-vision' })];
      return {
        protocol: 'vless',
        port: randomPort(),
        settings,
        streamSettings: realityStream('tcp'),
      };
    },
  },
  {
    id: 'vless-reality-grpc',
    titleKey: 'pages.inbounds.presets.vlessRealityGrpc.title',
    descKey: 'pages.inbounds.presets.vlessRealityGrpc.desc',
    needsRealityKeys: true,
    needsDomain: false,
    build: () => {
      const settings = createDefaultVlessInboundSettings();
      // gRPC transport can't carry the Vision flow (TCP-only) — leave it blank.
      settings.clients = [createDefaultVlessClient({ flow: '' })];
      return {
        protocol: 'vless',
        port: randomPort(),
        settings,
        streamSettings: realityStream('grpc'),
      };
    },
  },
  {
    id: 'hysteria2',
    titleKey: 'pages.inbounds.presets.hysteria2.title',
    descKey: 'pages.inbounds.presets.hysteria2.desc',
    needsRealityKeys: false,
    needsDomain: true,
    build: (domain) => {
      const settings = createDefaultHysteriaInboundSettings({ version: 2 });
      settings.clients = [createDefaultHysteriaClient()];
      const tls = TlsStreamSettingsSchema.parse({}) as Record<string, unknown>;
      tls.serverName = (domain ?? '').trim();
      tls.certificates = [emptyFileCert()];
      // Hysteria2 跑在 QUIC/HTTP3 上,ALPN 只能是 h3。TlsStreamSettings 的默认值
      // ['h2','http/1.1'] 是给 TCP-TLS 用的,带进分享链接后客户端会拿它发起 QUIC
      // 握手,ALPN 协商不上 —— 表现就是「别的协议都好,唯独 Hysteria2 连不通」。
      tls.alpn = ['h3'];
      return {
        protocol: 'hysteria',
        port: randomPort(),
        settings,
        streamSettings: {
          network: 'hysteria',
          security: 'tls',
          hysteriaSettings: HysteriaStreamSettingsSchema.parse({}),
          tlsSettings: tls,
          // Hysteria2 obfuscation wrapper — salamander with a random password
          // mirrors what the modal seeds when you pick hysteria by hand.
          finalmask: {
            tcp: [],
            udp: [{ type: 'salamander', settings: { password: RandomUtil.randomLowerAndNum(16) } }],
          },
        },
      };
    },
  },
  {
    id: 'trojan-tls',
    titleKey: 'pages.inbounds.presets.trojanTls.title',
    descKey: 'pages.inbounds.presets.trojanTls.desc',
    needsRealityKeys: false,
    needsDomain: true,
    build: (domain) => {
      const settings = createDefaultTrojanInboundSettings();
      settings.clients = [createDefaultTrojanClient()];
      return {
        protocol: 'trojan',
        // Random port instead of 443 so multiple TLS presets don't collide on
        // the same port (TLS works on any port; the cert is port-agnostic).
        port: randomPort(),
        settings,
        streamSettings: tlsStream(
          { network: 'tcp', tcpSettings: TcpStreamSettingsSchema.parse({ header: { type: 'none' } }) },
          domain,
        ),
      };
    },
  },
  {
    id: 'vmess-ws-tls',
    titleKey: 'pages.inbounds.presets.vmessWsTls.title',
    descKey: 'pages.inbounds.presets.vmessWsTls.desc',
    needsRealityKeys: false,
    needsDomain: true,
    build: (domain) => {
      const settings = createDefaultVmessInboundSettings();
      settings.clients = [createDefaultVmessClient()];
      const ws = WsStreamSettingsSchema.parse({ path: `/${RandomUtil.randomLowerAndNum(8)}` });
      return {
        protocol: 'vmess',
        // Random port (see trojan-tls): avoids colliding with another TLS
        // preset on 443. Behind a CDN you'd front this with 443 externally.
        port: randomPort(),
        settings,
        streamSettings: tlsStream({ network: 'ws', wsSettings: ws }, domain),
      };
    },
  },
];

export function getPreset(id: PresetId): InboundPreset | undefined {
  return INBOUND_PRESETS.find((p) => p.id === id);
}

export interface PresetSecretOpts {
  // Reality key pair (from GET /panel/api/server/getNewX25519Cert).
  realityPrivateKey?: string;
  realityPublicKey?: string;
  // Panel TLS cert paths + domain (from POST /panel/setting/all).
  certFile?: string;
  keyFile?: string;
  domain?: string;
  // Shared subscription id (from GET /panel/api/server/getCommonSubId) — when
  // set, stamps every client so one subscription URL aggregates all nodes.
  subId?: string;
}

// Inject the runtime secrets a preset can't bake in itself: the Reality key
// pair (fetched per inbound) and/or the panel's TLS cert + domain. Mutates and
// returns the row's streamSettings in place. Used by both the single-apply
// path (modal form) and the batch "add all recommended" path.
export function applyPresetSecrets(row: RawInboundRow, opts: PresetSecretOpts): RawInboundRow {
  if (opts.subId) {
    const settings = row.settings as Record<string, unknown> | undefined;
    const clients = settings?.clients;
    if (Array.isArray(clients)) {
      for (const c of clients) {
        if (c && typeof c === 'object') (c as Record<string, unknown>).subId = opts.subId;
      }
    }
  }
  const stream = row.streamSettings as Record<string, unknown> | undefined;
  if (!stream) return row;

  const reality = stream.realitySettings as Record<string, unknown> | undefined;
  if (reality) {
    if (opts.realityPrivateKey != null) reality.privateKey = opts.realityPrivateKey;
    if (opts.realityPublicKey != null) {
      const inner = (reality.settings as Record<string, unknown> | undefined) ?? {};
      inner.publicKey = opts.realityPublicKey;
      reality.settings = inner;
    }
  }

  const tls = stream.tlsSettings as Record<string, unknown> | undefined;
  if (tls) {
    if (opts.domain) tls.serverName = opts.domain;
    if (opts.certFile && opts.keyFile) {
      const certs = Array.isArray(tls.certificates)
        ? (tls.certificates as Record<string, unknown>[])
        : [];
      if (certs.length === 0) certs.push(emptyFileCert());
      certs[0].certificateFile = opts.certFile;
      certs[0].keyFile = opts.keyFile;
      tls.certificates = certs;
    }
  }
  return row;
}

// Chinese fallback copy used until the i18n keys are translated across every
// locale. The modal prefers t(titleKey) and only falls back to these.
export const PRESET_FALLBACK: Record<PresetId, { title: string; desc: string }> = {
  'vless-reality-vision': {
    title: 'VLESS + Reality (Vision)',
    desc: '主力首选 · 无需证书 · 抗封锁强，点完即用',
  },
  'vless-reality-grpc': {
    title: 'VLESS + Reality (gRPC)',
    desc: 'Reality 的 gRPC 变体 · 无需证书',
  },
  hysteria2: {
    title: 'Hysteria2',
    desc: '基于 QUIC，速度快 · 需域名与证书 · 需 sing-box/NekoBox 客户端（Xray 内核不支持）',
  },
  'trojan-tls': {
    title: 'Trojan + TLS',
    desc: '经典 TLS 伪装 · 需域名与证书',
  },
  'vmess-ws-tls': {
    title: 'VMess + WS + TLS',
    desc: '可走 CDN 中转 · 需域名与证书',
  },
};

