package integration

// isoCountries backs AvailableRegions -- see its doc comment for why this is the full ISO list.
var isoCountries = []Region{
	{"AD", "Andorra"},
	{"AE", "United Arab Emirates"},
	{"AF", "Afghanistan"},
	{"AG", "Antigua and Barbuda"},
	{"AI", "Anguilla"},
	{"AL", "Albania"},
	{"AM", "Armenia"},
	{"AO", "Angola"},
	{"AR", "Argentina"},
	{"AS", "American Samoa"},
	{"AT", "Austria"},
	{"AU", "Australia"},
	{"AW", "Aruba"},
	{"AX", "Åland Islands"},
	{"AZ", "Azerbaijan"},
	{"BA", "Bosnia and Herzegovina"},
	{"BB", "Barbados"},
	{"BD", "Bangladesh"},
	{"BE", "Belgium"},
	{"BF", "Burkina Faso"},
	{"BG", "Bulgaria"},
	{"BH", "Bahrain"},
	{"BI", "Burundi"},
	{"BJ", "Benin"},
	{"BM", "Bermuda"},
	{"BN", "Brunei"},
	{"BO", "Bolivia"},
	{"BR", "Brazil"},
	{"BS", "Bahamas"},
	{"BT", "Bhutan"},
	{"BW", "Botswana"},
	{"BY", "Belarus"},
	{"BZ", "Belize"},
	{"CA", "Canada"},
	{"CD", "DR Congo"},
	{"CF", "Central African Republic"},
	{"CG", "Congo"},
	{"CH", "Switzerland"},
	{"CI", "Côte d'Ivoire"},
	{"CL", "Chile"},
	{"CM", "Cameroon"},
	{"CN", "China"},
	{"CO", "Colombia"},
	{"CR", "Costa Rica"},
	{"CU", "Cuba"},
	{"CV", "Cabo Verde"},
	{"CY", "Cyprus"},
	{"CZ", "Czechia"},
	{"DE", "Germany"},
	{"DJ", "Djibouti"},
	{"DK", "Denmark"},
	{"DM", "Dominica"},
	{"DO", "Dominican Republic"},
	{"DZ", "Algeria"},
	{"EC", "Ecuador"},
	{"EE", "Estonia"},
	{"EG", "Egypt"},
	{"ER", "Eritrea"},
	{"ES", "Spain"},
	{"ET", "Ethiopia"},
	{"FI", "Finland"},
	{"FJ", "Fiji"},
	{"FM", "Micronesia"},
	{"FO", "Faroe Islands"},
	{"FR", "France"},
	{"GA", "Gabon"},
	{"GB", "United Kingdom"},
	{"GD", "Grenada"},
	{"GE", "Georgia"},
	{"GF", "French Guiana"},
	{"GH", "Ghana"},
	{"GI", "Gibraltar"},
	{"GL", "Greenland"},
	{"GM", "Gambia"},
	{"GN", "Guinea"},
	{"GP", "Guadeloupe"},
	{"GQ", "Equatorial Guinea"},
	{"GR", "Greece"},
	{"GT", "Guatemala"},
	{"GU", "Guam"},
	{"GW", "Guinea-Bissau"},
	{"GY", "Guyana"},
	{"HK", "Hong Kong"},
	{"HN", "Honduras"},
	{"HR", "Croatia"},
	{"HT", "Haiti"},
	{"HU", "Hungary"},
	{"ID", "Indonesia"},
	{"IE", "Ireland"},
	{"IL", "Israel"},
	{"IM", "Isle of Man"},
	{"IN", "India"},
	{"IQ", "Iraq"},
	{"IR", "Iran"},
	{"IS", "Iceland"},
	{"IT", "Italy"},
	{"JE", "Jersey"},
	{"JM", "Jamaica"},
	{"JO", "Jordan"},
	{"JP", "Japan"},
	{"KE", "Kenya"},
	{"KG", "Kyrgyzstan"},
	{"KH", "Cambodia"},
	{"KI", "Kiribati"},
	{"KM", "Comoros"},
	{"KN", "Saint Kitts and Nevis"},
	{"KP", "North Korea"},
	{"KR", "South Korea"},
	{"KW", "Kuwait"},
	{"KY", "Cayman Islands"},
	{"KZ", "Kazakhstan"},
	{"LA", "Laos"},
	{"LB", "Lebanon"},
	{"LC", "Saint Lucia"},
	{"LI", "Liechtenstein"},
	{"LK", "Sri Lanka"},
	{"LR", "Liberia"},
	{"LS", "Lesotho"},
	{"LT", "Lithuania"},
	{"LU", "Luxembourg"},
	{"LV", "Latvia"},
	{"LY", "Libya"},
	{"MA", "Morocco"},
	{"MC", "Monaco"},
	{"MD", "Moldova"},
	{"ME", "Montenegro"},
	{"MG", "Madagascar"},
	{"MH", "Marshall Islands"},
	{"MK", "North Macedonia"},
	{"ML", "Mali"},
	{"MM", "Myanmar"},
	{"MN", "Mongolia"},
	{"MO", "Macao"},
	{"MQ", "Martinique"},
	{"MR", "Mauritania"},
	{"MT", "Malta"},
	{"MU", "Mauritius"},
	{"MV", "Maldives"},
	{"MW", "Malawi"},
	{"MX", "Mexico"},
	{"MY", "Malaysia"},
	{"MZ", "Mozambique"},
	{"NA", "Namibia"},
	{"NC", "New Caledonia"},
	{"NE", "Niger"},
	{"NG", "Nigeria"},
	{"NI", "Nicaragua"},
	{"NL", "Netherlands"},
	{"NO", "Norway"},
	{"NP", "Nepal"},
	{"NR", "Nauru"},
	{"NZ", "New Zealand"},
	{"OM", "Oman"},
	{"PA", "Panama"},
	{"PE", "Peru"},
	{"PF", "French Polynesia"},
	{"PG", "Papua New Guinea"},
	{"PH", "Philippines"},
	{"PK", "Pakistan"},
	{"PL", "Poland"},
	{"PR", "Puerto Rico"},
	{"PS", "Palestine"},
	{"PT", "Portugal"},
	{"PW", "Palau"},
	{"PY", "Paraguay"},
	{"QA", "Qatar"},
	{"RE", "Réunion"},
	{"RO", "Romania"},
	{"RS", "Serbia"},
	{"RU", "Russia"},
	{"RW", "Rwanda"},
	{"SA", "Saudi Arabia"},
	{"SB", "Solomon Islands"},
	{"SC", "Seychelles"},
	{"SD", "Sudan"},
	{"SE", "Sweden"},
	{"SG", "Singapore"},
	{"SI", "Slovenia"},
	{"SK", "Slovakia"},
	{"SL", "Sierra Leone"},
	{"SM", "San Marino"},
	{"SN", "Senegal"},
	{"SO", "Somalia"},
	{"SR", "Suriname"},
	{"SS", "South Sudan"},
	{"ST", "São Tomé and Príncipe"},
	{"SV", "El Salvador"},
	{"SY", "Syria"},
	{"SZ", "Eswatini"},
	{"TC", "Turks and Caicos Islands"},
	{"TD", "Chad"},
	{"TG", "Togo"},
	{"TH", "Thailand"},
	{"TJ", "Tajikistan"},
	{"TL", "Timor-Leste"},
	{"TM", "Turkmenistan"},
	{"TN", "Tunisia"},
	{"TO", "Tonga"},
	{"TR", "Türkiye"},
	{"TT", "Trinidad and Tobago"},
	{"TV", "Tuvalu"},
	{"TW", "Taiwan"},
	{"TZ", "Tanzania"},
	{"UA", "Ukraine"},
	{"UG", "Uganda"},
	{"US", "United States"},
	{"UY", "Uruguay"},
	{"UZ", "Uzbekistan"},
	{"VA", "Vatican City"},
	{"VC", "Saint Vincent and the Grenadines"},
	{"VE", "Venezuela"},
	{"VI", "U.S. Virgin Islands"},
	{"VN", "Vietnam"},
	{"VU", "Vanuatu"},
	{"WS", "Samoa"},
	{"YE", "Yemen"},
	{"ZA", "South Africa"},
	{"ZM", "Zambia"},
	{"ZW", "Zimbabwe"},
}
