services:
  3xui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3xui_app_local
    volumes:
      - $PWD/db/:/etc/x-ui/
      - $PWD/cert/:/root/cert/
      - ./access.log:/app/access.log
      - ./error.log:/app/error.log
    environment:
      TZ: Asia/Shanghai
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
      XUI_KEEP_ACCESS_LOG: "true"
      XUI_SITE_NAME: "local"
    ports:
      - "2053:2053"
      - "2096:2096"
      - "1234:1234"
      - "1235:1235"
    cap_add:
      - NET_ADMIN  # Required for tc (traffic control) port speed limiting
    tty: true
    restart: unless-stopped
