package service

import (
	"encoding/json"

	"github.com/mhsanaei/3x-ui/v3/internal/util/random"
)

// shortIdLengths mirrors the frontend RandomUtil.randomShortIds() shape so a
// rotated set is indistinguishable from one generated by the panel's
// "randomize shortIds" button: hex strings of these lengths.
var shortIdLengths = []int{2, 4, 6, 8, 10, 12, 14, 16}

const secondsPerDay = 86400

// realityRotationDue reports whether a rotation anchored at lastUnix is due at
// nowUnix given an interval in days. A non-positive interval means disabled.
func realityRotationDue(lastUnix int64, intervalDays int, nowUnix int64) bool {
	if intervalDays <= 0 {
		return false
	}
	return nowUnix-lastUnix >= int64(intervalDays)*secondsPerDay
}

// freshShortIds builds a brand-new shortId set matching the panel's manual
// generator (one hex string per entry in shortIdLengths).
func freshShortIds() []string {
	ids := make([]string, len(shortIdLengths))
	for i, l := range shortIdLengths {
		ids[i] = random.Hex(l)
	}
	return ids
}

// RotateRealityStreamSettings applies any due Reality rotations to a raw
// streamSettings JSON string and returns the re-serialized JSON.
//
// shortId rotation (replace mode): when due, every shortId is replaced with a
// fresh set. publicKey rotation (opt-in, destructive): when due, genKeypair is
// called and the new private key + client public key are written back. On the
// first sighting of an enabled interval whose last-rotation anchor is zero, the
// anchor is set to now WITHOUT rotating, so enabling rotation does not trigger
// an immediate churn.
//
// changed reports whether streamSettings was modified at all (anchor writes
// included, so the anchor persists); restartNeeded reports whether xray must
// reload (true only when shortIds or the keypair actually changed). Non-reality
// streams are returned untouched with changed=false.
func RotateRealityStreamSettings(
	streamJSON string,
	now int64,
	genKeypair func() (priv string, pub string, err error),
) (newJSON string, changed bool, restartNeeded bool, err error) {
	if streamJSON == "" {
		return streamJSON, false, false, nil
	}

	var stream map[string]any
	if err = json.Unmarshal([]byte(streamJSON), &stream); err != nil {
		return streamJSON, false, false, err
	}

	if security, _ := stream["security"].(string); security != "reality" {
		return streamJSON, false, false, nil
	}
	reality, ok := stream["realitySettings"].(map[string]any)
	if !ok {
		return streamJSON, false, false, nil
	}
	rotation, ok := reality["rotation"].(map[string]any)
	if !ok {
		return streamJSON, false, false, nil
	}

	shortIdDays := jsonInt(rotation["shortIdDays"])
	publicKeyDays := jsonInt(rotation["publicKeyDays"])
	lastShortId := jsonInt64(rotation["lastShortIdRotation"])
	lastPublicKey := jsonInt64(rotation["lastPublicKeyRotation"])

	if shortIdDays > 0 {
		switch {
		case lastShortId == 0:
			rotation["lastShortIdRotation"] = now
			changed = true
		case realityRotationDue(lastShortId, shortIdDays, now):
			reality["shortIds"] = freshShortIds()
			rotation["lastShortIdRotation"] = now
			changed = true
			restartNeeded = true
		}
	}

	if publicKeyDays > 0 {
		switch {
		case lastPublicKey == 0:
			rotation["lastPublicKeyRotation"] = now
			changed = true
		case realityRotationDue(lastPublicKey, publicKeyDays, now):
			priv, pub, genErr := genKeypair()
			if genErr != nil {
				return streamJSON, changed, restartNeeded, genErr
			}
			reality["privateKey"] = priv
			if settings, ok := reality["settings"].(map[string]any); ok {
				settings["publicKey"] = pub
			} else {
				reality["settings"] = map[string]any{"publicKey": pub}
			}
			rotation["lastPublicKeyRotation"] = now
			changed = true
			restartNeeded = true
		}
	}

	if !changed {
		return streamJSON, false, false, nil
	}

	out, marshalErr := json.MarshalIndent(stream, "", "  ")
	if marshalErr != nil {
		return streamJSON, false, false, marshalErr
	}
	return string(out), changed, restartNeeded, nil
}

// jsonInt coerces a JSON-decoded number (float64) or int to int, defaulting to
// 0 for any other type.
func jsonInt(v any) int {
	switch n := v.(type) {
	case float64:
		return int(n)
	case int:
		return n
	case int64:
		return int(n)
	default:
		return 0
	}
}

// jsonInt64 coerces a JSON-decoded number (float64) or int to int64.
func jsonInt64(v any) int64 {
	switch n := v.(type) {
	case float64:
		return int64(n)
	case int:
		return int64(n)
	case int64:
		return n
	default:
		return 0
	}
}
